### ISSUE TITLE
Textures Inaccessible in Plugin for Blender 2.8

### ISSUE THREAD

**Issue by yearofthewhopper** [hsab/GrowthNodes#21]
Isn't able to access textures for blender 2.8
The traceback call looks like its referencing the wrong spot
```
Traceback (most recent call last):
  File "/Library/Application Support/Blender/2.8/scripts/addons/GrowthNodes-master/operators/bake.py", line 21, in execute
    node_tree.execute(refholder)
  File "/Library/Application Support/Blender/2.8/scripts/addons/GrowthNodes-master/node_tree/node_tree.py", line 280, in execute
    node.execute(refholder)
  File "/Library/Application Support/Blender/2.8/scripts/addons/GrowthNodes-master/nodes/geometry/displace.py", line 58, in execute
    texture = self.inputs[2].getTexture()
  File "/Library/Application Support/Blender/2.8/scripts/addons/GrowthNodes-master/sockets/texture2.py", line 164, in getTexture
    return bpy.data.textures[self.value]
KeyError: 'bpy_prop_collection[key]: key "" not found'
```

**Comment by itsKaspar** [comment]
Have you tried creating your own textures from the object dropdown menu ? last tab in the right menu
